function [] = generateAllJournalPlots(t_mean_diff, norm_trace_map, norm_regularity_map, ...
    norm_persist_map, filtered_coherence_map, x_sorted, y_sorted, t_sorted, coh_params, ...
    local_hot_mask, norm_trace_map_nofilt, filtered_coherence_map_raw, filtered_coherence_map_nogauss, ...
    filter_mask, threshold_diagnostic, ros_threshold, plotting_type)

    % GENERATEALLJOURNALPLOTS Creates plots for a journal article
    % 
    % [] = generateAllJournalPlots(t_mean_diff, norm_trace_map, norm_regularity_map, ...
    %     norm_persist_map, filtered_coherence_map, x_sorted, y_sorted, t_sorted, coh_params, ...
    %     local_hot_mask, norm_trace_map_nofilt, filtered_coherence_map_raw, filtered_coherence_map_nogauss, ...
    %     filter_mask, threshold_diagnostic, ros_threshold, plotting_type)
 

    journal.showScatterPlotOfRuleMaps3D(t_mean_diff,...
        ['Fully-Filtered-Single-Frame-Mean-IEI' plotting_type '.pdf'], false);
    journal.showScatterPlotOfRuleMaps(norm_trace_map,...
        ['Norm-Trace-Map-Sample-Density-Nominal-Rot' plotting_type '.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(norm_trace_map,...
        ['Norm-Trace-Map-Sample-Density-Nominal-Rot' plotting_type '-3D.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(norm_regularity_map,...
        ['Similarity-Map-Nominal-Rot' plotting_type '.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(norm_persist_map, ...
        ['Persistence-Map-Nominal-Rot' plotting_type '.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(filtered_coherence_map,...
        ['Coherence-Map-Nominal-Rot' plotting_type '.pdf'], false)
    journal.showScatterPlotOfHotPixelAccumulatorMap(norm_regularity_map,...
        ['Hot-Pixel-Accumulator-Map-Nominal-Rot' plotting_type '.pdf'], false);
    journal.show2DScatterOfLeakyBucketMap(x_sorted, y_sorted,norm_regularity_map<=coh_params.s_bnd, ...
        ['Hot-Pixel-Accumulator-Map-Nominal-Rot' plotting_type '-2D.pdf'], false);
    journal.showRegularityScoreHistogram(norm_regularity_map, ...
        ['Regularity-Score-Histogram-Nominal-Rot' plotting_type '.pdf'], false);
    journal.showScatterPlotOfEventVector(x_sorted, y_sorted, t_sorted,...
        ['Unfiltered-Event-Data-Nominal-Rot' plotting_type '.pdf'], false)
    journal.show2DScatterOfLeakyBucketMap(x_sorted, y_sorted, local_hot_mask,...
        ['Leaky-Bucket-Map-Nominal-Rot' plotting_type '.pdf'], false);
    journal.showScatterPlotOfRuleMaps3D(norm_trace_map_nofilt, ...
        ['Norm-Trace-Map-Sample-Density-w-Hot-Pixels-Nominal-Rot' plotting_type '-3D.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(filtered_coherence_map_raw, ...
        ['Norm-Coherence-Map-Unfiltered' plotting_type '-3D.pdf'], false)
    journal.showScatterPlotOfRuleMaps(filtered_coherence_map_raw, ...
        ['Norm-Coherence-Map-Unfiltered' plotting_type '.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(filter_mask, ...
        ['Norm-Coherence-Map-Gaussian-Only' plotting_type '-3D.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(filtered_coherence_map_nogauss, ...
        ['Norm-Coherence-Map-Gaussian' plotting_type '-3D.pdf'], false)
    journal.showScatterPlotOfRuleMaps3D(filtered_coherence_map, ...
        ['Norm-Coherence-Map-Gaussian-Filtered' plotting_type '-3D.pdf'], false)
    journal.showRosinThresholdConstructionNorm(threshold_diagnostic, ros_threshold, ...
        ['Rosin-Threshold-Construction-Norm' plotting_type '.pdf'], false);
    journal.showRosinScoreDistribution(threshold_diagnostic, ros_threshold, ...
        ['Rosin-Threshold-Distribution' plotting_type '.pdf'], false);

end